export const CONFIG_ERROR_CODES = {
  MISSING_PROJECT: 'MISSING_PROJECT',
  INVALID_PROJECT: 'INVALID_PROJECT',
  INVALID_BASE_URL: 'INVALID_BASE_URL',
  INVALID_LOGGING: 'INVALID_LOGGING',
  INVALID_RETRY: 'INVALID_RETRY',
  INVALID_ARTIFACTS: 'INVALID_ARTIFACTS',
  INVALID_EXTENSIONS: 'INVALID_EXTENSIONS',
  INVALID_CONFIG: 'INVALID_CONFIG',
  CONFIG_FILE_NOT_FOUND: 'CONFIG_FILE_NOT_FOUND',
  CONFIG_FILE_INVALID: 'CONFIG_FILE_INVALID',
} as const;

export type ConfigErrorCode = (typeof CONFIG_ERROR_CODES)[keyof typeof CONFIG_ERROR_CODES];
